"""Build native and lazy-loaded UI subsets from bundled Sarasa sources (fonttools)."""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
fonts = root / "src/cast.Desktop/Web/fonts"
options = subset.Options()
options.recalc_timestamp = False
options.name_IDs = ["*"]
options.name_languages = ["*"]
options.layout_features = ["*"]  # Retain tabular numerals and the source typography features.
ascii_text = "".join(chr(i) for i in range(32, 127))


def build(source, target, text):
    font = subset.load_font(str(fonts / source), options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(text=text)
    subsetter.subset(font)
    subset.save_font(font, str(fonts / target), options)


build("SarasaGothicSC-Regular.ttf", "SarasaGothicSC-Startup.ttf", ascii_text +
      "正在打开无法初始化超时请关闭后重试检查加载失败错误主界面准备完成串口工具已经运行。\n")

# Preserve the original full fonts as fallback for characters outside the UI subset.
# Collect source characters deterministically so labels and bundled preset names
# receive the same typeface without decoding the full CJK font on every startup.
characters = set(ascii_text)
for directory in [root / "src", root / "samples/presets"]:
    for path in sorted(directory.rglob("*")):
        if path.suffix in {".cs", ".html", ".js", ".json"} and not any(
                part in {"bin", "obj"} for part in path.parts):
            characters.update(path.read_text(encoding="utf-8-sig"))
with TTFont(fonts / "SarasaGothicSC-Regular.ttf") as source:
    supported = set(source.getBestCmap())
points = sorted(ord(char) for char in characters if ord(char) in supported)
text = "".join(chr(point) for point in points)
for weight in ["Regular", "Bold"]:
    build(f"SarasaGothicSC-{weight}.ttf", f"SarasaGothicSC-UI-{weight}.ttf", text)

ranges = []
start = previous = points[0]
for point in points[1:] + [None]:
    if point is not None and point == previous + 1:
        previous = point
        continue
    ranges.append(f"U+{start:X}" if start == previous else f"U+{start:X}-{previous:X}")
    start = previous = point
faces = []
for prefix in ["", "UI-"]:
    for weight, number in [("Regular", 400), ("Bold", 700)]:
        faces.append('@font-face {\n  font-family: "Sarasa Gothic SC";\n' +
                     f'  src: url("fonts/SarasaGothicSC-{prefix}{weight}.ttf") format("truetype");\n' +
                     f'  font-style: normal;\n  font-weight: {number};\n  font-display: swap;\n' +
                     ("  unicode-range: " + ",".join(ranges) + ";\n" if prefix else "") + "}\n")
(fonts.parent / "fonts.css").write_text(
    "/* Generated by scripts/Build-StartupFont.py; full fonts cover remaining glyphs. */\n" +
    "\n".join(faces), encoding="utf-8")
print(f"Generated startup and UI subsets ({len(points)} UI code points).")
